hashgraph/hedera-protobufs-java

- .gitignore
- pom.xml
- src/main/proto/BasicTypes.proto
- src/main/proto/ConsensusCreateTopic.proto
- src/main/proto/ConsensusDeleteTopic.proto
- src/main/proto/ConsensusGetTopicInfo.proto
- src/main/proto/ConsensusService.proto
- src/main/proto/ConsensusSubmitMessage.proto
- src/main/proto/ConsensusTopicDefinition.proto
- src/main/proto/ConsensusTopicState.proto
- src/main/proto/ConsensusUpdateTopic.proto
- src/main/proto/Query.proto
- src/main/proto/Response.proto
- src/main/proto/ResponseCode.proto
- src/main/proto/TransactionBody.proto
- src/main/proto/TransactionReceipt.proto
- Adds HCS protobuf definitions to the `hcs` branch.
- Appends `-hcs` to the artifact created
- Sets version at 0.1.0-SNAPSHOT
- Eliminates some maven warnings
> HCS protobuf definitions

- pom.xml
- src/main/proto/ConsensusCreateTopic.proto
- src/main/proto/ConsensusGetTopicInfo.proto
- src/main/proto/ConsensusService.proto
- src/main/proto/ConsensusTopicDefinition.proto
- src/main/proto/ConsensusTopicInfo.proto
- src/main/proto/ConsensusTopicState.proto
- src/main/proto/ConsensusUpdateTopic.proto
- src/main/proto/ResponseCode.proto
- src/main/proto/SystemDelete.proto
- src/main/proto/SystemUndelete.proto
Updated protobuf for the full release of HCS.
Fields that are marked as deprecated were deprecated between HCS 0.1 and now, and will be removed before official release.
> Feature/hcs 0.2

- docs/NestedDoc.html
- docs/NotNestedDoc.html
- docs/NotNestedDoc.md
- src/main/proto/BasicTypes.proto
- src/main/proto/ScheduleCreate.proto
- src/main/proto/ScheduleDelete.proto
- src/main/proto/ScheduleGetInfo.proto
- src/main/proto/ScheduleService.proto
- src/main/proto/ScheduleSign.proto
Adds docs to the new Schedule Service.
Closes [#135](https://github.com/LimeChain/hedera-services/issues/135)
> L0135 Add Schedule Service description

- src/main/proto/CryptoGetAccountBalance.proto
> Sync from hedera-protobufs

- src/main/proto/AccountBalanceFile.proto
- src/main/proto/BasicTypes.proto
- src/main/proto/CryptoGetAccountBalance.proto
> Token decimals in queries

- pom.xml
- src/main/proto/ResponseCode.proto
- src/main/proto/ScheduleGetInfo.proto
- src/main/proto/TokenCreate.proto
- src/main/proto/TransactionReceipt.proto
**Related issue(s):**
Closes #57
**Summary of the change:**
1. Added response code for HCS message size too large error;
> 00057 d hcs message size

- grab.sh
- pom.xml
- src/main/proto/BasicTypes.proto
- src/main/proto/ResponseCode.proto
- src/main/proto/SchedulableTransactionBody.proto
- src/main/proto/ScheduleCreate.proto
- src/main/proto/ScheduleDelete.proto
- src/main/proto/ScheduleGetInfo.proto
- src/main/proto/ScheduleSign.proto
- src/main/proto/TransactionBody.proto
> Update protobufs for 0.13.0-alpha.2

- src/main/proto/BasicTypes.proto
- src/main/proto/ResponseCode.proto
- src/main/proto/ThrottleDefinitions.proto
> (Sync with hedera-protobufs) New throttle defs.

- pom.xml
> Use alpha.3-SNAPSHOT

- pom.xml
- src/main/proto/AccountBalanceFile.proto
- src/main/proto/BasicTypes.proto
- src/main/proto/CryptoGetInfo.proto
- src/main/proto/FileAppend.proto
- src/main/proto/FileCreate.proto
- src/main/proto/FileDelete.proto
- src/main/proto/FileUpdate.proto
- src/main/proto/Query.proto
- src/main/proto/Response.proto
- src/main/proto/ResponseCode.proto
- src/main/proto/TokenAssociate.proto
- src/main/proto/TokenBurn.proto
- src/main/proto/TokenCreate.proto
- src/main/proto/TokenGetAccountNftInfo.proto
- src/main/proto/TokenGetInfo.proto
- src/main/proto/TokenGetNftInfo.proto
- src/main/proto/TokenGetNftInfos.proto
- src/main/proto/TokenMint.proto
- src/main/proto/TokenService.proto
- src/main/proto/TokenWipeAccount.proto
- src/main/proto/TransactionReceipt.proto
> Begin 0.16.0 dev iteration

- pom.xml
- src/main/proto/BasicTypes.proto
- src/main/proto/CryptoTransfer.proto
- src/main/proto/CustomFees.proto
- src/main/proto/Query.proto
- src/main/proto/Response.proto
- src/main/proto/ResponseCode.proto
- src/main/proto/TokenBurn.proto
- src/main/proto/TokenCreate.proto
- src/main/proto/TokenDissociate.proto
- src/main/proto/TokenFeeScheduleUpdate.proto
- src/main/proto/TokenGetAccountNftInfos.proto
- src/main/proto/TokenGetInfo.proto
- src/main/proto/TokenGetNftInfos.proto
- src/main/proto/TokenMint.proto
- src/main/proto/TokenService.proto
- src/main/proto/TokenUpdate.proto
- src/main/proto/TokenWipeAccount.proto
- src/main/proto/Transaction.proto
- src/main/proto/TransactionBody.proto
- src/main/proto/TransactionReceipt.proto
- src/main/proto/TransactionRecord.proto
> Begin 0170 dev iteration

- pom.xml
- src/main/proto/CustomFees.proto
- src/main/proto/Freeze.proto
- src/main/proto/ResponseCode.proto
> Prepare for 0.18.0 dev iteration

- pom.xml
- src/main/proto/basic_types.proto
- src/main/proto/contract_call_local.proto
- src/main/proto/contract_update.proto
- src/main/proto/freeze.proto
- src/main/proto/freeze_type.proto
- src/main/proto/response_code.proto
- src/main/proto/schedulable_transaction_body.proto
- src/main/proto/token_create.proto
- src/main/proto/token_get_info.proto
- src/main/proto/token_pause.proto
- src/main/proto/token_service.proto
- src/main/proto/token_unpause.proto
- src/main/proto/token_update.proto
- src/main/proto/transaction_body.proto
Sync from upstream `develop` branch.
> Sync from upstream

- src/main/proto/basic_types.proto
- src/main/proto/consensus_topic_info.proto
- src/main/proto/contract_call.proto
- src/main/proto/contract_call_local.proto
- src/main/proto/contract_get_info.proto
- src/main/proto/crypto_adjust_allowance.proto
- src/main/proto/crypto_approve_allowance.proto
- src/main/proto/crypto_get_info.proto
- src/main/proto/crypto_service.proto
- src/main/proto/file_get_info.proto
- src/main/proto/mirror_network_service.proto
- src/main/proto/response_code.proto
- src/main/proto/schedulable_transaction_body.proto
- src/main/proto/schedule_get_info.proto
- src/main/proto/token_create.proto
- src/main/proto/token_get_info.proto
- src/main/proto/token_get_nft_info.proto
- src/main/proto/token_update.proto
- src/main/proto/transaction_body.proto
- src/main/proto/transaction_get_receipt.proto
- src/main/proto/transaction_get_record.proto
- src/main/proto/transaction_record.proto
Several PRs merged in `hedera-protobufs` are not updated to `main` branch. This PR has all the changes grabbed using ` grab.sh` from the protobufs repo
> Update main to latest protobufs

- src/main/proto/basic_types.proto
- src/main/proto/crypto_delete_allowance.proto
- src/main/proto/crypto_service.proto
- src/main/proto/response_code.proto
- src/main/proto/schedulable_transaction_body.proto
- src/main/proto/token_get_nft_info.proto
- src/main/proto/transaction_body.proto
- src/main/proto/transaction_record.proto
https://github.com/hashgraph/hedera-protobufs/pull/168
> Allowance changes - Phase 1

- pom.xml
- src/main/proto/basic_types.proto
- src/main/proto/contract_create.proto
- src/main/proto/contract_get_info.proto
- src/main/proto/contract_update.proto
- src/main/proto/crypto_create.proto
- src/main/proto/crypto_get_info.proto
- src/main/proto/crypto_update.proto
- src/main/proto/get_account_details.proto
- src/main/proto/hash_object.proto
- src/main/proto/node_stake_update.proto
- src/main/proto/record_stream_file.proto
- src/main/proto/response_code.proto
- src/main/proto/sidecar_file.proto
- src/main/proto/signature_file.proto
- src/main/proto/transaction_body.proto
- src/main/proto/transaction_record.proto
Pulled latest changes from `main`
> 0.27.0  changes

- pom.xml
> update pom file  latest version 0.37-snapshot

- docs/NotNestedDoc.html
- docs/NotNestedDoc.md
- pom.xml
- src/main/proto/state/file/file.proto
- src/main/proto/state/token/account.proto
- src/main/proto/state/token/token.proto
- src/main/proto/state/token/token_relation.proto
> Use hedera-protobufs v0.38.0

- docs/NotNestedDoc.html
- docs/NotNestedDoc.md
- pom.xml
- src/main/proto/state/file/file.proto
- src/main/proto/state/recordcache/recordcache.proto
- src/main/proto/state/token/account.proto
- src/main/proto/transaction.proto
> release 0.39.0 change

- docs/NotNestedDoc.html
- docs/NotNestedDoc.md
- pom.xml
- src/main/proto/state/blockrecords/block_info.proto
> Update to 0.45

- pom.xml
Changes to protobuf java for release version v0.49.0
> Release 49

- docs/NotNestedDoc.html
- docs/NotNestedDoc.md
- pom.xml
- src/main/proto/basic_types.proto
- src/main/proto/response_code.proto
- src/main/proto/token_update.proto
Changes for `hedera-protobufs-java` release 0.50. All files are auto-generated from `hedera-protobufs` 0.50 code except for `pom.xml`.
> 50.0 release

- docs/NotNestedDoc.html
- docs/NotNestedDoc.md
- pom.xml
- src/main/proto/crypto_create.proto
- src/main/proto/crypto_update.proto
- src/main/proto/response_code.proto
> chore: deploy 0.51 protobuf to sonatype

- pom.xml
- src/main/proto/address_book_service.proto
- src/main/proto/basic_types.proto
- src/main/proto/contract_create.proto
- src/main/proto/contract_update.proto
- src/main/proto/node_create.proto
- src/main/proto/node_delete.proto
- src/main/proto/node_update.proto
- src/main/proto/query.proto
- src/main/proto/response_code.proto
- src/main/proto/schedulable_transaction_body.proto
- src/main/proto/state/addressbook/node.proto
- src/main/proto/token_reject.proto
- src/main/proto/token_service.proto
- src/main/proto/token_update_nfts.proto
- src/main/proto/transaction_body.proto
- src/main/proto/transaction_receipt.proto
> Release 0.52.0 changes

- pom.xml
- src/main/proto/basic_types.proto
- src/main/proto/response_code.proto
- src/main/proto/schedulable_transaction_body.proto
- src/main/proto/state/token/account.proto
- src/main/proto/state/token/account_pending_airdrop.proto
- src/main/proto/token_airdrop.proto
- src/main/proto/token_cancel_airdrop.proto
- src/main/proto/token_claim_airdrop.proto
- src/main/proto/token_service.proto
- src/main/proto/transaction_body.proto
- src/main/proto/transaction_record.proto
Signed-off-by: Derek Riley <derek.riley@swirldslabs.com>
> chore: Release 0.53.0 deploy to maven

- .github/CODEOWNERS
Description: Updates CODEOWNERS
Fixes: #147
> ci: Q3 Audit Tasks -- Updated CODEOWNERS

- docs/NotNestedDoc.html
- docs/NotNestedDoc.md
- pom.xml
- src/main/proto/address_book_service.proto
- src/main/proto/block_service.proto
- src/main/proto/node_update.proto
Updates to docs for release 56. This builds on PR #157 which added block stream proto files.
> Release 56 changes

- docs/NotNestedDoc.html
- docs/NotNestedDoc.md
- pom.xml
- src/main/proto/basic_types.proto
- src/main/proto/block_service.proto
- src/main/proto/event/gossip_event.proto
- src/main/proto/node_delete.proto
- src/main/proto/node_update.proto
- src/main/proto/response_code.proto
- src/main/proto/state/blockstream/block_stream_info.proto
- src/main/proto/state/roster/roster.proto
- src/main/proto/state/schedule/schedule.proto
- src/main/proto/stream/output/block_header.proto
- src/main/proto/stream/output/smart_contract_service.proto
- src/main/proto/stream/output/state_changes.proto
- src/main/proto/stream/record_file_item.proto
- src/main/proto/token_get_info.proto
- src/main/proto/transaction_body.proto
- src/main/proto/transaction_receipt.proto
> chore: Update 57 version

- pom.xml
> update to release 0.57

- pom.xml
- src/main/proto/token_get_info.proto
> chore: added token_get_info.proto change to 57

- .github/CODEOWNERS
Updating the CODEOWNERS file.
Closes #160
> ci: Update CODEWONERS file

- .github/CODEOWNERS
> chore: Update to replace devops-ci with platform-ci

- pom.xml
> Release 58.4

- pom.xml
- src/main/proto/stream/output/crypto_service.proto
- src/main/proto/stream/output/transaction_output.proto
Includes protobuf changes for release 0.59.1
> chore: Release 0.59.1
